user: apache
group: apache
pid: /var/run/ledgerrb/thin.pid
log: /var/log/ledgerrb/thin.log
timeout: 30
max_conns: 1024
port: 9292
max_persistent_conns: 512
environment: production
adapter: rack
servers: 1
daemonize: true
tag: ledgerrb