# user: apache
# group: apache
pid: thin.pid
log: thin.log
timeout: 30
max_conns: 1024
port: 9292
max_persistent_conns: 512
environment: production
adapter: rack
servers: 1
daemonize: true
tag: ledgerrb